### PR TITLE
Added NgrokConfiguration class

### PR DESCRIPTION
**Pull request by s-frei**
As discussed in #52 

I additionally added 'lombok' to improve readability and avoid boilerplate. Its an compile-time annotation processor, if you don't know that already. I hope you are fine with that, when not I could remove it again. I not applied the given annotations everywhere, only in the classes I touched.

Let me know what you think about the code changes 😉 

grafik

Sidenote: The *NgrokRunnerWithConfigFileTest* is failing on my side but I think this is not caused by my changes, or am I wrong?

### CODE REVIEW

**Comment by s-frei** [comment]
Since I added a `@ConditionalOnBean` to the *auto-configuration* multiple MockTests are failing. I haven't already figured out how to fix them, they confuse me a bit.

**Comment by kilmajster** [comment]
Hi, fitst of all - big thanks for contribution 🙂 I think I managed to fix issues you were facing with, please check MR that I created into your fork (https://github.com/s-frei/ngrok-spring-boot-starter/pull/1). I put there also some explenations about what I did. If you will be ok with the changes please update this MR to kickoff CI and I will merge that and release new version 😁

**Comment by s-frei** [comment]
Thanks again for your PR 😉 When contributing is always handled like this, I'm for sure willing to do more!
Where to discuss additional features? Should I just open an issue?

*Sidenote*: After merging your PR I applied *Lombok* where possible. Thought you would be fine with that since you haven't declined yet :)

**Comment by kilmajster** [comment]
One more time thanks for contribution! 😀 Glad to hear you are ready to help more, as you can already see, after diving into the code, there are things that can be improved 🙂 I just promoted new release v0.3.6 so your changes should be available in the central repository soon 😀 Regarding new ideas/features I think issues + MR would be enough.

And about this lombok, it's fine for me, I just didn't add it in the beginning and it stayed like this

**Pull request merged**
